select * from customer 
--Q1. What is the total revenue generated by male vs. female customers?

SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT "Customer ID","Purchase Amount (USD)" FROM customer
WHERE "Discount Applied" = 'Yes' AND "Purchase Amount (USD)">=(SELECT AVG("Purchase Amount (USD)")FROM customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT "Item Purchased", AVG("Review Rating") AS avg_rating FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;

select * from customer
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select "Shipping Type" , avg("Purchase Amount (USD)") from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select ("Subscription Status"),avg("Purchase Amount (USD)") as ,sum(("Purchase Amount (USD)")) from customer
group by "Subscription Status"

---- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes') * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
  END AS customer_segment,
  COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category? 
SELECT "Category",
       "Item Purchased",
       total_orders
FROM (
    SELECT "Category",
           "Item Purchased",
           COUNT(*) AS total_orders,
           DENSE_RANK() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT(*) DESC
           ) AS rnk
    FROM customer
    GROUP BY "Category", "Item Purchased"
) 
WHERE rnk <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    "Subscription Status" ,
    COUNT(*) AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group? 
select "Age",sum("Purchase Amount (USD)") as Total_Revenue
from customer 
group by "Age"
order by Total_Revenue desc




























